### ISSUE TITLE
this library not work

### ISSUE THREAD

**Issue by winos** [KevinTCoughlin/node-randomuser#4] opened 2016-04-23 12:03 UTC
i can not see some result when i execute the script ./example.js

**Comment by KevinTCoughlin** [comment] 2016-04-23 20:33
Works for me. Closing since I can't reproduce.

```shell
λ node examples\demo.js
[ { gender: 'female',
    name: { title: 'mrs', first: 'elizabete', last: 'lima' },
    location:
     { street: '5042 rua principal',
       city: 'cabo frio',
       state: 'santa catarina',
       postcode: 96579 },
    email: 'elizabete.lima@example.com',
    login:
     { username: 'brownelephant935',
       password: 'bearcat',
       salt: '1EuAvN1N',
       md5: 'bde29d1ec07685f1d15921c4de9fec24',
       sha1: '6a2c07847650bc4df6485ed774920429ea14923e',
       sha256: '668e39e6307ae9d65c23dea4cd53038f3328fd5fbf620e370711739c9be2d548' },
    registered: 1269216768,
    dob: 700221512,
    phone: '(66) 4238-2304',
    cell: '(46) 1502-7975',
    id: { name: '', value: null },
    picture:
     { large: 'https://randomuser.me/api/portraits/women/40.jpg',
       medium: 'https://randomuser.me/api/portraits/med/women/40.jpg',
       thumbnail: 'https://randomuser.me/api/portraits/thumb/women/40.jpg' },
    nat: 'BR' },
  { gender: 'female',
    name: { title: 'ms', first: 'kayla', last: 'andrews' },
    location:
     { street: '1395 springfield road',
       city: 'carrigaline',
       state: 'idaho',
       postcode: 11174 },
    email: 'kayla.andrews@example.com',
    login:
     { username: 'lazygorilla858',
       password: 'nightwin',
       salt: 'IU1XbFWj',
       md5: 'c92fde58da8322ceb132fb52600a51d0',
       sha1: 'ae1e198856b6004e01cd0344f7f2abf8b046996c',
       sha256: 'b650585ea6b1ae5dc2278cd5a348a5dc454d7b0cf8afce6a885bde82f0f3a5e3' },
    registered: 1060595714,
    dob: 93516909,
    phone: '051-861-4095',
    cell: '081-526-0199',
    id: { name: 'PPS', value: '8783557T' },
    picture:
     { large: 'https://randomuser.me/api/portraits/women/96.jpg',
       medium: 'https://randomuser.me/api/portraits/med/women/96.jpg',
       thumbnail: 'https://randomuser.me/api/portraits/thumb/women/96.jpg' },
    nat: 'IE' },
  { gender: 'male',
    name: { title: 'mr', first: 'mehmet', last: 'aydan' },
    location:
     { street: '2741 kushimoto sk',
       city: 'tekirdağ',
       state: 'isparta',
       postcode: 29656 },
    email: 'mehmet.aydan@example.com',
    login:
     { username: 'ticklishpanda376',
       password: 'athena',
       salt: 'doleibjJ',
       md5: 'badc97863b5c67cfc550560a37e5d132',
       sha1: '3e8bb9f650ca19f8f52746ee40ea917c05fa0b47',
       sha256: 'e20fb50db1826f851566966b2750461c860bfd81281832ef92d42ef733ba69a2' },
    registered: 1218812279,
    dob: 171485276,
    phone: '(142)-158-0882',
    cell: '(751)-313-4430',
    id: { name: '', value: null },
    picture:
     { large: 'https://randomuser.me/api/portraits/men/44.jpg',
       medium: 'https://randomuser.me/api/portraits/med/men/44.jpg',
       thumbnail: 'https://randomuser.me/api/portraits/thumb/men/44.jpg' },
    nat: 'TR' },
  { gender: 'female',
    name: { title: 'ms', first: 'maddison', last: 'sims' },
    location:
     { street: '5177 denny street',
       city: 'kinsale',
       state: 'arizona',
       postcode: 32554 },
    email: 'maddison.sims@example.com',
    login:
     { username: 'redkoala603',
       password: 'fellatio',
       salt: 'dpg0y631',
       md5: 'ae12ebab74b0670f51bed90418194559',
       sha1: '25517d32f82b07a32a7d8549892640a5593ce956',
       sha256: 'a6aa1d4c98d3925fd0aad8a0ea74ed3f8cd074eba720fa1e3012e7429bff7bc4' },
    registered: 1419877026,
    dob: 330042371,
    phone: '041-353-9516',
    cell: '081-128-3917',
    id: { name: 'PPS', value: '7601225T' },
    picture:
     { large: 'https://randomuser.me/api/portraits/women/90.jpg',
       medium: 'https://randomuser.me/api/portraits/med/women/90.jpg',
       thumbnail: 'https://randomuser.me/api/portraits/thumb/women/90.jpg' },
    nat: 'IE' },
  { gender: 'male',
    name: { title: 'mr', first: 'carlos', last: 'gallego' },
    location:
     { street: '8080 calle nebrija',
       city: 'torrevieja',
       state: 'comunidad valenciana',
       postcode: 19525 },
    email: 'carlos.gallego@example.com',
    login:
     { username: 'smallmouse129',
       password: 'sunday',
       salt: 'v44P8pS5',
       md5: 'aee189635c66d105eb051a8884582967',
       sha1: '1da9640ba3988a942debfa5242bc9ff0fc650909',
       sha256: 'd300c2e47736a736aa71a854349a4730e932335e0ca9770e7e6901c64cf8a338' },
    registered: 1122701062,
    dob: 295468907,
    phone: '948-991-395',
    cell: '655-646-377',
    id: { name: 'DNI', value: '62646610-M' },
    picture:
     { large: 'https://randomuser.me/api/portraits/men/65.jpg',
       medium: 'https://randomuser.me/api/portraits/med/men/65.jpg',
       thumbnail: 'https://randomuser.me/api/portraits/thumb/men/65.jpg' },
    nat: 'ES' } ]
[ { gender: 'female',
    name: { title: 'miss', first: 'florence', last: 'grewal' },
    location:
     { street: '3133 st. lawrence ave',
       city: 'wellington',
       state: 'nova scotia',
       postcode: 35175 },
    email: 'florence.grewal@example.com',
    login:
     { username: 'beautifulmeercat406',
       password: 'smokey1',
       salt: 'G8nc6Qd4',
       md5: 'b6e16df98d064a7539dc5ee0d3918c96',
       sha1: 'b802e90a37e1fccdc40b37e9794560ccbf8fd1aa',
       sha256: 'b4cbf2ebb6451ec748b2c6ce486b259929e71d999de1b7cf43b1378f268c1721' },
    registered: 1303664204,
    dob: 100415676,
    phone: '002-217-0204',
    cell: '818-470-1037',
    id: { name: '', value: null },
    picture:
     { large: 'https://randomuser.me/api/portraits/women/13.jpg',
       medium: 'https://randomuser.me/api/portraits/med/women/13.jpg',
       thumbnail: 'https://randomuser.me/api/portraits/thumb/women/13.jpg' },
    nat: 'CA' } ]
```

**Closed by KevinTCoughlin** 2016-04-23 20:33 UTC

**Comment by winos** [comment] 2016-04-23 22:37
Hi Kevin, but i can see the error, you should change the mainendpoint API. The current does not working.

```js
// success
this.options = {
        baseURL: 'https://randomuser.me/api/'
    };
// fail
this.options = {
        baseURL: 'http://api.randomuser.me/'
    };

**Comment by winos** [comment] 2016-04-23 22:58
Kevin update is the module in npm, currently the install from donwload a old version.

> npm i randomuser --save

```js
  this.options = {
        baseURL: 'http://randomuser.me/g/'
    };
`
fixed it please ;)

**Comment by KevinTCoughlin** [comment] 2016-04-24 08:44
@winos `1.1.0` has been published to [npm](https://www.npmjs.com/package/randomuser). Thanks for the reminder.

**Comment by winos** [comment] 2016-04-24 19:05
Thank u so much!!
